### ISSUE TITLE
Releasing Human Evaluation Data

### ISSUE THREAD

**Issue by roskoN** [golsun/SpaceFusion#1]
Hello,

First of all, many thanks and kudos for the great work! It is a really interesting research.

I am also working on research related to the dialogue systems and one of the issues I am investigating is automated dialogue evaluation. Do you think, you could release the human evaluation data (dialogues and human scores) on all of the models (baselines + SpaceFusion)?

Kind Regards

**Comment by golsun** [comment]
sorry we are currently not planning to release of human evaluation data. apologize for the late reply.
